# Generated by Django 5.2.1 on 2025-09-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
